replicaCount: 2

image:
  repository: ghcr.io/curiouslearning/literacy-data-api
  tag: master
  pullPolicy: Always

container:
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/app/var/secrets/keys/bigquery-serviceaccount.json"
    - name: MEMCACHE_DNS
      value: "lit-data-memcached"
    - name: MEMCACHE_PORT
      value: "11211"

volumes:
  - name: keys
    secret:
      secretName: bigquery-serviceaccount

service:
  port: 80
